Transform: AWS::Serverless-2016-10-31
Parameters:
  Subdomain:
    Type: String
    MinLength: 1
  APIGatewayURL:
    Type: String
    MinLength: 1
Resources:
  S3WebFrontend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
        - .
        - - Ref: Subdomain
          - ia.webfrontend
          - com
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  CloudFrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment:
          Fn::Sub: Identity to access ${Subdomain}.ia.webfrontend.com from CloudFront
  CloudfrontS3Policy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
    - CloudFrontIdentity
    - S3WebFrontend
    Properties:
      Bucket:
        Ref: S3WebFrontend
      PolicyDocument:
        Statement:
          Action:
          - s3:GetObject
          Effect: Allow
          Principal:
            CanonicalUser:
              Fn::GetAtt:
              - CloudFrontIdentity
              - S3CanonicalUserId
          Resource:
            Fn::Join:
            - /
            - - Fn::GetAtt:
                - S3WebFrontend
                - Arn
              - '*'
  CDN:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - CloudFrontIdentity
    - S3WebFrontend
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - Id: S3Origin
          DomainName:
            Fn::GetAtt:
            - S3WebFrontend
            - DomainName
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
              - /
              - - origin-access-identity/cloudfront
                - Ref: CloudFrontIdentity
        - Id: APIGateway
          DomainName:
            Ref: APIGatewayURL
          OriginPath: /Prod
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
