Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  MasterUsername:
    Type: String
    Default: root
  MasterUserPassword:
    Type: String
    Default: Entranc3$
    NoEcho: true
  Env:
    Type: String
    Default: dev

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DeletionProtection: true
      Engine: mysql #Make this MySQL!
      EngineVersion: '8.0'
      DBName: IA_VoiceSynth
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.small
    DeletionPolicy: Snapshot
